"""Telegram Guest Bot — the *guest's* agent surface for the live A2A demo.

This is the lightweight second bot. The main bot
(@Rosewood_sandhill_hap_bot) plays HEART (the property's concierge).
This one (@Rosewood_sandhill_guest_bot) plays the GUEST's personal
agent. In a group chat where both bots live, the orchestrator posts
voice messages from each bot, alternating turns, so the audience
literally hears two agents negotiate.

Run alongside the main bot:
    python telegram_guest_bot.py

Commands it answers:
    /start   — identifies itself as the guest agent
    /chatid  — replies with the chat_id (works in groups too)
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

load_dotenv(_HERE / ".env", override=True)

from telegram import Update  # noqa: E402
from telegram.constants import ParseMode  # noqa: E402
from telegram.ext import (  # noqa: E402
    Application,
    CommandHandler,
    ContextTypes,
)

TOKEN = os.environ.get("TELEGRAM_GUEST_BOT_TOKEN", "")


async def cmd_start(update: Update, ctx: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message is None:
        return
    await update.message.reply_text(
        "🤖 *Guest Agent · Telegram surface*\n\n"
        "I represent the *guest* in the live A2A demo. In a group chat, I'll "
        "negotiate with @Rosewood\\_sandhill\\_hap\\_bot (HEART) on the guest's "
        "behalf — with voices generated by ElevenLabs.\n\n"
        "Use /chatid in any chat (private or group) to grab the chat\\_id the "
        "orchestrator needs.",
        parse_mode=ParseMode.MARKDOWN,
    )


async def cmd_chatid(update: Update, ctx: ContextTypes.DEFAULT_TYPE) -> None:
    chat = update.effective_chat
    if chat is None or update.message is None:
        return
    title = chat.title or chat.first_name or ""
    await update.message.reply_text(
        f"🆔 *Chat ID*\n\n"
        f"`{chat.id}`\n\n"
        f"_type:_ {chat.type}\n"
        f"_title:_ {title}\n\n"
        "Pass this to the voice orchestrator.",
        parse_mode=ParseMode.MARKDOWN,
    )


def main() -> None:
    if not TOKEN:
        print("ERROR: TELEGRAM_GUEST_BOT_TOKEN not set in server/.env", flush=True)
        sys.exit(1)
    print(f"Starting Guest Bot (token: {TOKEN[:10]}…)", flush=True)
    app = Application.builder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", cmd_start))
    app.add_handler(CommandHandler("chatid", cmd_chatid))
    print("Listening (long-polling). Send /start from Telegram.", flush=True)
    app.run_polling()


if __name__ == "__main__":
    main()
