"use client";

import { useEffect, useState } from "react";
import { CommChain } from "@/components/CommChain";
import { StaffBrief } from "@/components/StaffBrief";
import { AuditLogStream } from "@/components/AuditLogStream";
import { TelegramPanel } from "@/components/TelegramPanel";
import { LiveGuestAgent } from "@/components/LiveGuestAgent";
import { A2AConversation } from "@/components/A2AConversation";
import { ConnectedAgents } from "@/components/ConnectedAgents";
import { GuestMemoryViewer } from "@/components/GuestMemoryViewer";
import { Button } from "@/components/ui/button";

const OPS_HAPCONSOLE = "http://localhost:5560/ops?view=hapconsole&chrome=0";

export default function HapConsolePage() {
  const [briefVisible, setBriefVisible] = useState(false);
  const [auditOpen, setAuditOpen] = useState(false);

  useEffect(() => {
    // If rendered inside the unified HEART Platform shell, ask it to activate
    // the dedicated HAP Console tab so the sidebar stays in sync with the iframe.
    if (typeof window !== "undefined" && window.parent && window.parent !== window) {
      try {
        window.parent.postMessage(
          { type: "heart-platform:navigate", module: "hapconsole" },
          "*"
        );
      } catch {}
    }
  }, []);

  return (
    <div className="max-w-[1400px] mx-auto px-10 py-14">
      {/* header */}
      <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-10">
        <div>
          <div className="text-[0.7rem] uppercase tracking-[0.32em] text-bronze mb-3">
            Rosewood Sand Hill · The View
          </div>
          <h1 className="font-serif text-6xl text-ink leading-[1.05] tracking-tight">
            HAP Console
          </h1>
          <p className="text-ink/65 mt-5 max-w-2xl text-lg leading-relaxed">
            Five actors. One open protocol. Watch the guest&apos;s agent and
            ours negotiate the stay — in the open, in real time, with the human
            in the loop.
          </p>
        </div>
      </div>

      {/* connected MCP-style agents — "apps with access" surface */}
      <div className="mb-5">
        <ConnectedAgents />
      </div>

      {/* live telegram channel — proves the chain is real */}
      <div className="mb-5">
        <TelegramPanel />
      </div>

      {/* live guest agent — what Claude is learning from the conversation */}
      <div className="mb-5">
        <LiveGuestAgent />
      </div>

      {/* live A2A — the two Claudes talking via the HAP tools */}
      <div className="mb-5">
        <A2AConversation />
      </div>

      {/* guest.md — portable memory owned by the guest */}
      <div className="mb-7">
        <GuestMemoryViewer />
      </div>

      {/* main comm chain */}
      <CommChain onStaffBriefReady={() => setBriefVisible(true)} />

      {/* staff brief — appears when concierge generates suggestions */}
      <div className="mt-10 grid grid-cols-1 lg:grid-cols-[2fr_3fr] gap-7">
        <div className="space-y-5">
          <div>
            <div className="text-[0.7rem] uppercase tracking-[0.28em] text-bronze mb-2">
              What lands at the desk
            </div>
            <h2 className="font-serif text-3xl text-ink leading-tight">
              The Staff Brief
            </h2>
            <p className="text-ink/60 mt-3 text-sm leading-relaxed">
              No login. No app. The brief is what staff actually receives when
              the handshake completes — written for the human at the desk, not
              for the guest.
            </p>
          </div>
          <div className="text-[0.72rem] tracking-wide text-ink/55 space-y-2 pl-4 border-l border-bronze/25">
            <p>
              <span className="text-bronze uppercase tracking-[0.18em] mr-2">
                Note
              </span>
              Calendar contents stay on the guest&apos;s device. Only the
              <em> visit purpose </em> is shared with the property.
            </p>
            <p>
              <span className="text-bronze uppercase tracking-[0.18em] mr-2">
                Note
              </span>
              The brief is generated by Claude Sonnet 4.5 against the property&apos;s
              Sense of Place RAG and the active flow profile.
            </p>
          </div>
        </div>
        <StaffBrief visible={briefVisible} />
      </div>

      {/* HEART operational event stream — the live shared /ops feed, merged in
          so the unified HAP Console module surfaces both views as one. */}
      <div className="mt-14 border-t border-bronze/15 pt-8">
        <div className="mb-4">
          <div className="text-[0.7rem] uppercase tracking-[0.28em] text-bronze mb-1.5">
            Operational stream
          </div>
          <h3 className="font-serif text-2xl text-ink">HEART event feed · live</h3>
          <p className="text-ink/55 text-sm mt-2 max-w-2xl leading-relaxed">
            Every HAP event recorded by the HEART runtime — the same shared feed
            staff watches at the front desk, embedded here for protocol observers.
          </p>
        </div>
        <div className="border border-bronze/20 rounded-sm overflow-hidden bg-white">
          <iframe
            src={OPS_HAPCONSOLE}
            title="HEART HAP event stream"
            className="w-full"
            style={{ height: 620, border: 0 }}
          />
        </div>
      </div>

      {/* audit log — collapsible for the developers / compliance eye */}
      <div className="mt-12 border-t border-bronze/15 pt-8">
        <div className="flex items-center justify-between mb-4">
          <div>
            <div className="text-[0.7rem] uppercase tracking-[0.28em] text-bronze mb-1.5">
              Compliance lens
            </div>
            <h3 className="font-serif text-2xl text-ink">Raw HAP audit stream</h3>
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={() => setAuditOpen((v) => !v)}
            className="border-bronze/40 text-bronze hover:bg-bronze/10 uppercase tracking-[0.18em] text-[0.7rem]"
          >
            {auditOpen ? "Hide" : "Show"} audit log
          </Button>
        </div>
        {auditOpen && (
          <div className="animate-fade-in-up">
            <AuditLogStream />
            <p className="text-ink/45 text-xs mt-3 italic">
              The stream is hash-chained. Each entry references the previous
              hash, so tampering breaks the chain. Retention on guest data: 0
              days. Retention on operational signal: indefinite (pseudonymous).
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
